name: cadetbank
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: 2.2.0
  go_router: 10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    # - assets/animations/
    # - assets/json_data/
  
  fonts:
    - family: Jeko
      fonts:
        - asset: assets/fonts/Jeko-Extra-Light.otf
          weight: 200
        - asset: assets/fonts/Jeko-Light.otf
          weight: 300
        - asset: assets/fonts/Jeko-Regular.otf
          weight: 400
        - asset: assets/fonts/Jeko-Medium.otf
          weight: 500
        - asset: assets/fonts/Jeko-Semi-Bold.otf
          weight: 600
        - asset: assets/fonts/Jeko-Bold.otf
          weight: 700
        - asset: assets/fonts/Jeko-Extra-Bold.otf
          weight: 800
        - asset: assets/fonts/Jeko-Black.otf
          weight: 900
    - family: CerebriSansPro
      fonts:
        - asset: assets/fonts/CerebriSansPro-Thin.otf
          weight: 100
        - asset: assets/fonts/CerebriSansPro-Extra-Light.otf
          weight: 200
        - asset: assets/fonts/CerebriSansPro-Light.otf
          weight: 300
        - asset: assets/fonts/CerebriSansPro-Regular.otf
          weight: 400
        - asset: assets/fonts/CerebriSansPro-Medium.otf
          weight: 500
        - asset: assets/fonts/CerebriSansPro-Semi-Bold.otf
          weight: 600
        - asset: assets/fonts/CerebriSansPro-Bold.otf
          weight: 700
        - asset: assets/fonts/CerebriSansPro-Extra-Bold.otf
          weight: 800
    - family: CerebriSansPro-Heavy
      fonts:
        - asset: assets/fonts/CerebriSansPro-Heavy.otf
    - family: CerebriSansPro-Book
      fonts:
        - asset: assets/fonts/CerebriSansPro-Book.otf
